//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeCoverage.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VsPerfCmd.exe")]
        public string VsPerfCmdExePath {
            get {
                return ((string)(this["VsPerfCmdExePath"]));
            }
            set {
                this["VsPerfCmdExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/start:coverage /output:{0}")]
        public string StartVsPerfCmdExeArgs {
            get {
                return ((string)(this["StartVsPerfCmdExeArgs"]));
            }
            set {
                this["StartVsPerfCmdExeArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/shutdown")]
        public string StopVsPerfCmdExeArgs {
            get {
                return ((string)(this["StopVsPerfCmdExeArgs"]));
            }
            set {
                this["StopVsPerfCmdExeArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReportGenerator.exe")]
        public string ReportGeneratorExePath {
            get {
                return ((string)(this["ReportGeneratorExePath"]));
            }
            set {
                this["ReportGeneratorExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-reports:{0} -targetdir:{1}")]
        public string ReportGeneratorExeArgs {
            get {
                return ((string)(this["ReportGeneratorExeArgs"]));
            }
            set {
                this["ReportGeneratorExeArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe")]
        public string BrowserExePath {
            get {
                return ((string)(this["BrowserExePath"]));
            }
            set {
                this["BrowserExePath"] = value;
            }
        }
    }
}
