//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeCoverage.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VsPerfCmd.exe")]
        public string VsPerfCmdExePath {
            get {
                return ((string)(this["VsPerfCmdExePath"]));
            }
            set {
                this["VsPerfCmdExePath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/start:coverage /output:{0} /CS /USER:{1}")]
        public string StartVsPerfCmdExeArgs {
            get {
                return ((string)(this["StartVsPerfCmdExeArgs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/shutdown")]
        public string StopVsPerfCmdExeArgs {
            get {
                return ((string)(this["StopVsPerfCmdExeArgs"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ReportGenerator.exe")]
        public string ReportGeneratorExePath {
            get {
                return ((string)(this["ReportGeneratorExePath"]));
            }
            set {
                this["ReportGeneratorExePath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-reports:{0} -targetdir:{1}")]
        public string ReportGeneratorExeArgs {
            get {
                return ((string)(this["ReportGeneratorExeArgs"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe")]
        public string BrowserExePath {
            get {
                return ((string)(this["BrowserExePath"]));
            }
            set {
                this["BrowserExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VsInstr.exe")]
        public string VsInstrExePath {
            get {
                return ((string)(this["VsInstrExePath"]));
            }
            set {
                this["VsInstrExePath"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} /coverage")]
        public string VsInstrExeArgs {
            get {
                return ((string)(this["VsInstrExeArgs"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Acharya")]
        public string AppPoolIdentity {
            get {
                return ((string)(this["AppPoolIdentity"]));
            }
            set {
                this["AppPoolIdentity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> ListOfAssemblies {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["ListOfAssemblies"]));
            }
            set {
                this["ListOfAssemblies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iisreset")]
        public string RestartIIS {
            get {
                return ((string)(this["RestartIIS"]));
            }
            set {
                this["RestartIIS"] = value;
            }
        }
    }
}
